stages:
  data_ingestion:
    cmd: python -m src.youtubeViewerSentimentAnalysis.data.data_ingestion
    deps:
    - src/youtubeViewerSentimentAnalysis/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw