stages:
  data_ingestion:
    cmd: python -m src.youtubeViewerSentimentAnalysis.data.data_ingestion
    deps:
    - src/youtubeViewerSentimentAnalysis/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python -m src.youtubeViewerSentimentAnalysis.data.data_preprocessing
    deps:
    - data/raw/train.csv
    - data/raw/test.csv
    - src/youtubeViewerSentimentAnalysis/data/data_preprocessing.py
    outs:
    - data/interim