stages:
  data_ingestion:
    cmd: python -m src.youtubeViewerSentimentAnalysis.data.data_ingestion
    deps:
    - src/youtubeViewerSentimentAnalysis/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python -m src.youtubeViewerSentimentAnalysis.data.data_preprocessing
    deps:
    - data/raw/train.csv
    - data/raw/test.csv
    - src/youtubeViewerSentimentAnalysis/data/data_preprocessing.py
    outs:
    - data/interim

  model_building:
    cmd: python -m src.youtubeViewerSentimentAnalysis.model.model_building
    deps:
    - data/interim/train_processed.csv
    - src/youtubeViewerSentimentAnalysis/model/model_building.py
    params:
    - model_building.max_features
    - model_building.ngram_range
    - model_building.learning_rate
    - model_building.max_depth
    - model_building.n_estimators
    outs:
    - lgbm_model.pkl
    - tfidf_vectorizer.pkl

  model_evaluation:
    cmd: python -m src.youtubeViewerSentimentAnalysis.model.model_evaluation
    deps:
    - lgbm_model.pkl
    - tfidf_vectorizer.pkl
    - data/interim/train_processed.csv
    - data/interim/test_processed.csv
    - src/youtubeViewerSentimentAnalysis/model/model_evaluation.py
    outs:
    - experiment_info.json